### ISSUE TITLE
where to find bnk files that matches SoundNames_automata.csv?

### ISSUE THREAD

**Issue by C4nf3ng** [NSACloud/NieR-Audio-Tools#2]
where to find bnk files that matches SoundNames_automata.csv?
I have extracted all bnk files in /data/sound jp releases but none of them matches SoundNames_automata.csv, is this csv file just work for english release?

By the way another 2 questions 
1 how did you get SoundNames_automata.csv
2 is this SoundNames_automata.csv completed? only 400+ voice related to 2b

**Comment by NSACloud** [comment]
BNKs are packed into the dat files, you can extract them with platinumDat or nier2blender

JP names weren't included because of an issue with parsing

1. I generated a list of all wem ids called by the events inside all of the bnk files and assigned them them the name used by the event
2. It's not 100% complete but most of the voice lines are labeled
